name: build-push-gcr
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-push-to-gcr-service-account:
    name: Build & push - with service account
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: test
      PROJECT_ID: prj-diameterhealth-working
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}'
          # project_id: ${{ env.PROJECT_ID }}
          # export_default_credentials: true
      
      - name: build image
        run: docker build -t $IMAGE_NAME:latest .
      
      - name: configure docker client
        run: |-
          gcloud auth configure-docker --quiet
      
      - name: push to gcr
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest